---
name: Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: ["1.19"]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Verify go mod
      run: make go-mod-verify

    - name: Lint
      uses: golangci/golangci-lint-action@v3

    - name: Test
      run: make test VERBOSE=1 CODECOV=1

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: coverage.txt
      if: matrix.go == '1.19'
